---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: expressjs-k8s
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.3
spec:
  chart:
    repository: https://charts.cloudposse.com/incubator/
    name: monochart
    version: 0.23.2

  values:
    image:
      repository: nginx
      tag: alpine

    deployment:
      enabled: true

    service:
      enabled: true
      ports:
        default:
          internal: 80
          external: 80
